export type MockServerData = {
  title          : string []   ;
  description    : string []   ;
  createdDate    : string []   ;
  city           : string []   ;
  cover          : string []   ;
  pictures       : string []   ;
  premium        : string []   ;
  favorites      : string []   ;
  rating         : string []   ;
  type           : string []   ;
  numberRooms    : string []   ;
  numberGuests   : string []   ;
  price          : string []   ;
  amenities      : string []   ;
  author         : string []   ;
  numberComments : string []   ;
  coordinates    : string []   ;
};